//! Raw FFI bindings to [wlroots](https://gitlab.freedesktop.org/wlroots/wlroots) 0.20.
//!
//! This crate is generated by `bindgen` at build time against the wlroots headers
//! installed on the build machine. It exposes wlroots exactly as C sees it: raw
//! pointers, no lifetimes, no `Drop`, no safety. A safe wrapper belongs in a
//! separate crate layered on top.
//!
//! # Requirements
//!
//! * wlroots **0.20.x** with development headers, discoverable as the pkg-config
//!   module `wlroots-0.20`. Other minor versions are rejected at build time:
//!   wlroots has no stable ABI, so each minor release gets its own `wlr-sys` minor.
//! * `libclang`, for bindgen.
//! * The `wayland-scanner` binary. Two of wlroots' public headers include
//!   generated `wlr-protocols` headers that wlroots does not install, so this
//!   crate vendors the protocol XML and regenerates them.
//!
//! # Ecosystem types
//!
//! Types that cross the boundary into other libraries are *not* generated here.
//! They are re-exported from the ecosystem's `-sys` crates so that a
//! `*mut wl_display` from this crate is the same Rust type as everywhere else:
//!
//! | Types | Source |
//! |---|---|
//! | `wl_display`, `wl_listener`, `wl_signal`, `wl_list`, `wl_resource`, ... | [`wayland_sys`] |
//! | `xkb_keymap`, `xkb_state`, `xkb_keysym_t`, ... | [`xkbcommon_sys`] |
//! | `libinput_device`, ... (with `libinput-backend`) | [`input_sys`] |
//!
//! Two families are generated locally instead, for the same reason in both cases
//! — a mismatched layout there would be silent memory corruption rather than a
//! compile error, and no maintained crate offers a type we can verify:
//!
//! * **pixman.** `pixman-sys` is unmaintained at 0.1.0, and `pixman_region32_t`
//!   is embedded *by value* in wlroots structs.
//! * **`drmModeModeInfo`.** This is libdrm's userspace struct from
//!   `<xf86drmMode.h>`; `drm-sys` only generates the kernel uAPI header and
//!   exposes the distinct `drm_mode_modeinfo`.
//!
//! The core Wayland protocol enums (`wl_output_transform`, `wl_seat_capability`,
//! `wl_shm_format`, ...) are also generated locally, because `wayland-sys` does
//! not provide them.
//!
//! # Feature detection
//!
//! wlroots' optional subsystems are compile-time flags baked into the installed
//! library. Each is bound only if its Cargo feature is enabled *and* the installed
//! library reports it available; a mismatch is a build warning, not an error.
//! What actually got bound is reported with `cfg`s, so downstream code should
//! test those rather than the features:
//!
//! ```ignore
//! #[cfg(wlr_has_xwayland)]
//! unsafe { wlr_sys::wlr_xwayland_create(display, compositor, true) };
//! ```
//!
//! Emitted cfgs: `wlr_has_drm_backend`, `wlr_has_x11_backend`,
//! `wlr_has_libinput_backend`, `wlr_has_session`, `wlr_has_gles2_renderer`,
//! `wlr_has_vulkan_renderer`, `wlr_has_xwayland`, `wlr_has_color_management`,
//! `wlr_has_gbm_allocator`, `wlr_has_udmabuf_allocator`.
//!
//! # Events
//!
//! wlroots' entire event model runs through `wl_signal` and `wl_listener`, whose
//! helpers are `static inline` in `wayland-server-core.h` and therefore have no
//! symbols to link against. See the [`signal`] module and the
//! [`container_of!`](crate::container_of) macro.

#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]
#![allow(clippy::missing_safety_doc)]
// wlroots' own doc comments carry bare URLs, which bindgen copies verbatim.
#![allow(rustdoc::bare_urls)]
#![doc(html_root_url = "https://docs.rs/wlr-sys/0.20.0")]

pub mod list;
pub mod signal;

pub use list::wl_list_iter;
pub use signal::{wl_signal_add, wl_signal_emit_mutable, wl_signal_get, wl_signal_init};

// Re-exported so downstream crates can name the shared ecosystem types without
// depending on each `-sys` crate directly.
#[cfg(feature = "libinput-backend")]
pub use input_sys;
pub use wayland_sys;
pub use xkbcommon_sys;

mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

pub use bindings::*;
