#![doc = include_str!("../README.md")]
#![doc = r#"
# See also

* [`signal`] — `wl_signal` / `wl_listener` helpers with no linkable symbol
* [`list`], [`container_of!`](crate::container_of) and
  [`wl_list_for_each!`](crate::wl_list_for_each) — intrusive-list plumbing
* Re-exported ecosystem crates: [`wayland_sys`], [`xkbcommon_sys`], and
  `input_sys` with the `libinput-backend` feature
"#]
// `wl_list_iter` is deliberately snake_case, mirroring the C names this crate
// binds; the rest come from bindgen's output.
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]

pub mod list;
pub mod signal;

pub use list::wl_list_iter;
pub use signal::{wl_signal_add, wl_signal_emit_mutable, wl_signal_get, wl_signal_init};

// Re-exported so downstream crates can name the shared ecosystem types without
// depending on each `-sys` crate directly.
//
// Gated on the *cfg*, not the feature: the libinput types are only blocklisted
// and imported when the installed wlroots actually has the backend, so gating on
// the feature alone would expose `input_sys` in a configuration where no wlroots
// API speaks its types.
#[cfg(wlr_has_libinput_backend)]
pub use input_sys;
pub use wayland_sys;
pub use xkbcommon_sys;

/// The ecosystem types wlroots' API speaks, re-exported at the crate root.
///
/// These are *not* generated by bindgen — they are the very types from
/// [`wayland_sys`], [`xkbcommon_sys`] and `input_sys`, blocklisted during binding
/// generation so that a `*mut wl_listener` here is the same Rust type as
/// everywhere else in the ecosystem. They arrive in the generated module through
/// a private `use`, which does not re-export, so they are named explicitly here:
/// without this block `wlr_sys::wl_listener` would not exist, even though every
/// consumer needs to declare one to receive a callback.
///
/// `tests/interop.rs` pins the identity claim at compile time.
mod ecosystem {
    #[cfg(wlr_has_libinput_backend)]
    pub use input_sys::{libinput, libinput_device, libinput_tablet_tool};
    pub use wayland_sys::common::{wl_array, wl_fixed_t, wl_interface, wl_list, wl_message};
    pub use wayland_sys::server::{
        wl_client, wl_display, wl_event_loop, wl_event_source, wl_global, wl_listener,
        wl_notify_func_t, wl_resource, wl_shm_buffer, wl_signal,
    };
    pub use xkbcommon_sys::{
        xkb_context, xkb_keymap, xkb_keysym_t, xkb_layout_index_t, xkb_led_index_t, xkb_led_mask_t,
        xkb_mod_index_t, xkb_mod_mask_t, xkb_rule_names, xkb_state,
    };
}

pub use ecosystem::*;

#[allow(clippy::missing_safety_doc)]
// wlroots' own doc comments carry bare URLs, which bindgen copies verbatim.
#[allow(rustdoc::bare_urls)]
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

pub use bindings::*;
